version: '2'
networks:
  default:
     external:
        name: grafana_network
services:
  grafana-storage:
    image: graphiteapp/graphite-statsd
    volumes:
      - /var/lib/grafana
  grafana:
    image: grafana/grafana
    env_file:
      - settings/grafana.env
    volumes_from:
      - grafana-storage
    ports:
      - "3000:3000"
  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - "80:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
  harvey:
    build: .
    env_file:
      - settings/harvey.env
    depends_on:
      - "graphite"